export type DemonstrationKind = "jack" | "usb" | "interface" | "learn" | "select" | "grid" | "line" | "hold" | "access" | "pair" | "startup";
export type DemoPlatform = "windows" | "macos" | "linux";

export function demonstration(kind: DemonstrationKind, platform: DemoPlatform) {
  const location = platform === "macos" ? "menu bar" : "system tray";
  const examples = {
    jack: { title: "Connect a jack switch", steps: ["Check which connector and socket your switch interface requires. This illustration uses socket 1 as an example.", "Insert the compatible switch plug fully into the interface.", "Connect the interface to your computer, then use Add switch to learn the key it sends."] },
    interface: { title: "Choose a keyboard mode on your interface", steps: ["Most switch interfaces have a mode switch or setting. Mouse-click and gamepad modes cannot be learned as switches, so Switchify sees nothing when you press.", "Choose the keyboard mode. Most interfaces send Space and Enter in this mode, and Switchify learns those.", "Choose Add switch, then press and release your switch. The key it sends appears as a badge.", "Assigned keys stay reserved while Switchify runs. If your interface can be programmed, set it to F13 or higher, which nothing else types."] },
    usb: { title: "Connect a USB switch", steps: ["A USB switch or keyboard interface sends a key when you press the switch.", "Connect it to a compatible USB port on your computer.", "Choose Add switch and learn its key. Connecting the cable alone does not configure Switchify."] },
    learn: { title: "Learn a switch key", steps: ["Choose Add switch, then Learn key to open the capture dialog.", "Press and release your physical switch once.", "The key it sends appears in the editor. F13 is only an example; your switch may send a different key."] },
    select: { title: "Assign Select", steps: ["After learning a key, open its Press and release action list.", "Choose Select so a short press and release chooses the highlighted item.", "Save the switch. Automatic scanning needs Select; manual scanning also needs Next and Previous."] },
    grid: { title: "Automatic grid then line scanning", steps: ["Focus the application you want to control. Press and release Select to start automatic scanning.", "Rows highlight in turn. Press and release Select to choose a row.", "Cells in that row highlight in turn. Press and release Select to choose a cell.", "Choose the horizontal position with Select as the vertical line moves across the cell.", "Choose the vertical position with Select as the horizontal line moves down the cell.", "With Auto select enabled, a countdown starts: wait for a left click, or press a switch to open the action menu.", "With Auto select disabled, the action menu opens immediately. Choose an action with Select. After a click, Select starts a new scan."] },
    line: { title: "Automatic line-only scanning", steps: ["Focus the application you want to control. Press and release Select to start automatic scanning.", "Choose the horizontal position with Select as the vertical line moves across the display.", "Choose the vertical position with Select as the horizontal line moves down the display.", "With Auto select enabled, wait through the countdown for a left click, or press a switch to open the action menu.", "With Auto select disabled, the action menu opens immediately. Choose an action with Select. After a click, Select starts a new scan."] },
    hold: { title: "Press, hold and release", steps: ["Press your switch briefly. Movement freezes while the switch is down.", "Release it to run its Press and release action, such as Select.", "Hold the switch longer to move through its configured hold actions. Scanning movement stays frozen.", "Keep holding until the action you want is offered. The actions shown here are examples, not your assignments.", "Release to execute the offered hold action. Holding never executes the offered action by itself; the emergency hold resets scanning."] },
    access: { title: "Allow Accessibility on macOS", steps: ["Choose Open Accessibility Settings in Switchify PC.", "In System Settings, open Privacy & Security, then Accessibility, and find Switchify PC.", "Enable Switchify PC, then return to the app so it can check access. This illustration does not grant permission."] },
    pair: { title: "Pair a mobile device", steps: ["Open Switchify on your mobile device and choose this computer while it is advertising.", "Compare the six-digit codes in both apps. These are example codes, not a live pairing request.", "Approve on this computer only if the codes match. If they differ or you did not request pairing, reject the request.", "A successful pairing trusts the mobile device. Check the real connection status in the app."] },
    startup: { title: "Understand startup behavior", steps: ["Start with system is optional. Choose whether Switchify should launch when you sign in.", `When enabled, Switchify starts quietly in the ${location}.`, `Open Switchify from the ${location} when you need its window. Start manually means opening the app yourself.`] },
  };
  const captions: Record<DemonstrationKind, string[]> = {
    jack: ["Check the connector.", "Plug in your switch.", "Connect the interface. Then add your switch."],
    interface: ["Find the mode switch.", "Choose the keyboard mode.", "Press your switch to learn its key.", "Program F13 or higher to avoid clashes."],
    usb: ["Your switch sends a key.", "Plug it into your computer.", "Add your switch and learn its key."],
    learn: ["Choose Add switch, then Learn key.", "Press and release your switch.", "Check the key shown."],
    select: ["Open Press and release.", "Choose Select.", "Save your switch."],
    grid: ["Press Select to start.", "Select a row.", "Select a cell.", "Select the horizontal position.", "Select the vertical position.", "Auto select: wait to click, or press for actions.", "Without Auto select: choose an action."],
    line: ["Press Select to start.", "Select the horizontal position.", "Select the vertical position.", "Auto select: wait to click, or press for actions.", "Without Auto select: choose an action."],
    hold: ["Press to freeze movement.", "Release to choose.", "Hold to see more actions.", "Wait for the action you want.", "Release to run it."],
    access: ["Open Accessibility Settings.", "Find Switchify PC.", "Turn it on, then return here."],
    pair: ["Choose this computer on your mobile.", "Compare the codes in both apps.", "Approve only if the codes match.", "Check the connection status."],
    startup: ["Choose whether to start at sign-in.", `Switchify starts in the ${location}.`, `Open its window from the ${location}.`],
  };
  return { ...examples[kind], captions: captions[kind] };
}
