import {
  type ScanningController,
  type PointScanConfig,
  validSwitches,
} from "../scanning/useScanning";

import { SettingGroup, Toggle, OptionGroup, secondsOptions } from "./controls";

const phases = {
  keyboard: "Choose a keyboard row, then a key",
  keyboardSuspended: "Select to resume the keyboard",
  keyboardOpening: "Opening the keyboard",
  idle: "Ready to begin",
  autoSelecting: "Waiting to click. Press a switch for the action menu",
  menu: "Choose an action at the selected point",
  menuSuspended: "Select to resume the action menu",
  dragDestination: "Choose drag destination",
  dragConfirmation: "Confirm drag",
  executing: "Performing drag",
  row: "Choose a row",
  cell: "Choose a cell",
  rowEscape: "Select to return to rows",
  x: "Choose the horizontal position",
  y: "Choose the vertical position",
};

export function ScanningSection({
  controller,
}: {
  controller: ScanningController;
}) {
  const { state, config, pending, error, update, retry, unsaved } = controller;

  const disabled = !state?.supported;

  return (
    <>
      <SettingGroup
        title="Scanning"
        description="Use switches connected to this computer to select a point on the screen."
      >
        <p>
          Focus the application you want to use, then press Select to scan the
          display under the pointer. Choose the X position, then the Y position
          to choose a point. Use the action menu for clicks, scrolling and dragging, or enable Auto select to click after a delay.
        </p>

        <p>
          Scanning is on whenever a switch has the Select action, and its keys
          stay reserved while Switchify runs. Escape resets the scan. Android
          connections pause local scanning until they end.
        </p>
        <p className="setting-note">
          On Windows, assigned keys remain switches with Shift, Ctrl, Alt or
          Windows held, even while Switchify is in the background. Other keys
          and shortcuts generated by Switchify still work normally.
        </p>

        <p role="status">
          {state?.enabled
            ? `${state.paused ? "Paused. " : ""}${phases[state.phase]}.`
            : (state?.message ?? "Loading point scan...")}
        </p>

        <p role="status">
          {pending
            ? "Saving scanning settings..."
            : unsaved
              ? "Scanning settings have unsaved changes."
              : "Scanning settings save automatically."}
        </p>

        {error && <p role="alert">{error}</p>}

        {error && unsaved && (
          <button
            type="button"
            className="secondary"
            disabled={!!pending || !validSwitches(config)}
            onClick={retry}
          >
            Retry save
          </button>
        )}

        {!validSwitches(config) && (
          <p role="alert">
            Each switch action needs a different key. Escape is reserved for
            cancel.
          </p>
        )}
      </SettingGroup>

      <SettingGroup
        title="Scan movement"
        description="Movement and switch actions shared by scanning techniques."
      >
        <Toggle
          label="Automatic scanning"
          checked={config.automatic}
          disabled={disabled}
          onChange={(value) => update("automatic", value)}
        />

        <OptionGroup<number>
          legend="Auto scan rate"
          disabled={disabled}
          value={config.blockIntervalMs}
          onChange={(value) => update("blockIntervalMs", value)}
          options={secondsOptions([
            250, 500, 750, 1000, 1500, 2000, 3000, 4000, 5000,
          ])}
          note={{
            summary: "How long each grid row, grid cell, or action-menu item stays highlighted before scanning moves on automatically. Shorter times scan faster; longer times give you more time to select. Line speed controls how fast the scanning lines move.",
          }}
        />

        <p>Assign switch actions in the Switches page. All actions run on release. Holding a switch freezes movement. After clicking, or after three passes without a selection, use Select to start again.</p>

      </SettingGroup>

      <SettingGroup title="Auto selection" description="Automatically left-click the chosen point after a delay. Press a switch again during the delay to open the action menu.">
        <Toggle label="Word prediction" checked={config.wordPrediction} disabled={disabled} onChange={(value) => update("wordPrediction", value)} />
        <Toggle label="Auto select" checked={config.autoSelectEnabled} disabled={disabled} onChange={(value) => update("autoSelectEnabled", value)} />
        {config.autoSelectEnabled && <label className="exact-speed">
          <span>Auto select delay (seconds)</span>
          <input type="number" min="0.1" max="100" step="0.1" disabled={disabled} value={config.autoSelectDelayMs / 1000}
            onChange={(event) => { if (event.currentTarget.validity.valid && event.currentTarget.value !== "") update("autoSelectDelayMs", Math.round(event.currentTarget.valueAsNumber * 1000)); }} />
        </label>}
      </SettingGroup>

      <SettingGroup title="Scanner colour" description="Choose the colour used by the grid, scanning lines, and action menu.">
        <fieldset disabled={disabled}>
          <legend>Scanner colour</legend>
          <div className="scanner-colours">
            {(["red", "green", "blue", "yellow", "white"] as const).map((colour) => (
              <label key={colour}>
                <input type="radio" name="scanner-colour" value={colour} checked={config.scannerColor === colour} onChange={() => update("scannerColor", colour)} />
                <span className={`color-swatch ${colour}`} aria-hidden="true" />
                <span>{colour[0].toUpperCase() + colour.slice(1)}</span>
              </label>
            ))}
          </div>
        </fieldset>
        <div className={`scanner-sample ${config.scannerColor}`} role="img" aria-label={`${config.scannerColor} scanner highlight sample`}>
          <span className="scanner-sample-selection">Selected area</span>
        </div>
      </SettingGroup>

      <SettingGroup
        title="Point scan"
        description="Choose how the scanning lines find a point. Changes apply straight away."
      >
        <OptionGroup<PointScanConfig["mode"]>
          legend="Mode"
          disabled={disabled}
          value={config.mode}
          onChange={(value) => update("mode", value)}
          options={[
            { value: "line", label: "Line only" },
            { value: "grid", label: "Grid then line" },
          ]}
        />

        <OptionGroup<number>
          legend="Line speed"
          columns="five"
          disabled={disabled}
          value={config.speed}
          onChange={(value) => update("speed", value)}
          options={["Very slow", "Slow", "Medium", "Fast", "Very fast"].map(
            (label, value) => ({ label, value }),
          )}
        />

        {config.mode === "grid" && (
          <>
            <label className="exact-speed">
              <span>Grid size</span>
              <select
                disabled={disabled}
                value={config.gridSize}
                onChange={(event) =>
                  update("gridSize", Number(event.target.value))
                }
              >
                {Array.from({ length: 9 }, (_, i) => i + 2).map((n) => (
                  <option key={n} value={n}>
                    {n} × {n}
                  </option>
                ))}
              </select>
            </label>
          </>
        )}

        <p>Settings are saved and scanning resumes when the app restarts.</p>
      </SettingGroup>
    </>
  );
}
